#!/bin/bash

username=$(whiptail --inputbox "Enter the username to change the password for:" 8 40 3>&1 1>&2 2>&3)

# Check if user exists
if id "$username" &>/dev/null; then

    password=$(whiptail --passwordbox "Enter the new password:" 8 40 3>&1 1>&2 2>&3)
    
# Change the user password
    echo "$username:$password" | sudo chpasswd
    
    whiptail --msgbox "Password for user $username has been changed." 8 40
else
    whiptail --msgbox "User $username does not exist." 8 40
fi
