#!/bin/bash

username=$(whiptail --inputbox "Enter the username to disable:" 8 40 3>&1 1>&2 2>&3)

# Check if user exists, disable if it does
if id "$username" &>/dev/null; then
    sudo usermod -L "$username"
    whiptail --msgbox "User $username has been disabled." 8 40
else
    whiptail --msgbox "User $username does not exist." 8 40
fi

